BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "dispositivo" (
	"id"	INTEGER NOT NULL UNIQUE,
	"cordx"	INTEGER NOT NULL,
	"cordy"	INTEGER NOT NULL,
	"instalacao"	INTEGER,
	"tipo"	TEXT NOT NULL DEFAULT 'N/A',
	"idproximo"	INTEGER,
	FOREIGN KEY("idproximo") REFERENCES "dispositivo",
	PRIMARY KEY("id")
);
COMMIT;
